### ISSUE TITLE
UI bug, etc

### ISSUE THREAD

**Issue by dukedase** [mati-k/EMT#5]
When you click the UI to add required missions, it opens up a small blank box. Clicking again will keep opening them. I can't find any way to close them. 

I also had the middle UI that visualizes the mission tree get closed, and couldn't figure out how to open it back up. I couldn't find any buttons or hotkeys.

The provinces to highlight, trigger, and effect UIs also do not work, when I click to add single or group it just gives a blank box I can click on but not type or select anything.

**Comment by mati-k** [comment]
Hey, sorry for late response

1. You can delete them by selecting them and clicking delete key. If you have some additional way of removing them or making it more intuitive i can change it

2. Not sure, it should always be open, if you have some way for me to replicate i can take a look

3. They should've been disabled, leftover from previous versions. Fixed and right click shouldn't show anything on them now
