### ISSUE TITLE
Mission recognition

### ISSUE THREAD

**Issue by JFK20** [mati-k/EMT#6]
potential_on_load gets recognised as a mission but it shouldnt be because its just a modifier for a branch.
Saving now becomes impossible because it has no Icon. When you set an icon it becomes an mission.

![image](https://github.com/mati-k/EMT/assets/51886126/60dfa525-125d-4c82-a564-06bd6234e369)

edit: I nearly fixed it but  i need a default value for potential_on_load

**Comment by mati-k** [comment]
Hey, sorry for late reply, forgot to look at repo.

Pushed fix for it, don't think default value is needed. Did it for regular potential so users don't have to retype tag = AAA every time, but on_load i've seen mostly used in vanilla MTs, and doubt people will change that often. So leaving it as saved if was already in, otehrwise not added.

**Comment by JFK20** [comment]
Thanks. I really appreciate that you still maintain this repo.

**Comment by JFK20** [comment]
Thanks. I really appreciate that you still maintain this repo.
