### ISSUE TITLE
Adding Mission itself to Required Missions crashes.

### ISSUE THREAD

**Issue by Crazedseal** [mati-k/EMT#8]
G'day,

If you add the current mission to its won required missions it will freeze and crash the program, thereby losing unsaved progress (I have accidently done this a few times).

It'd be preferable if it did not crash rather display an error, clear the input, and continue on.

Quick reproduction is:
1. Add mission.
2. Click new_mission.
3. Add new_mission to its own required missions.

![image](https://github.com/user-attachments/assets/722c6647-655f-4a08-b26d-ee299cf7afc4)

Cheers.

**Comment by mati-k** [comment]
Should be fixed in new version
